<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder {
    public function run(): void {
        DB::table('products')->insert([
            [
                'name' => 'Street Food Burguer Porn',
                'total_price' => 20.00,
                'categories_id' => 1,
                'image' => '../../img/foodPorn.jpg',
                'ubication' => 'Calle Hola 1',
                'capacity' => 100,
                'user_id' => 1,
                'visible' => true, // Nuevo campo
            ],
            [
                'name' => 'La Mafia Se Sienta A La Mesa',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/Mafia.png',
                'ubication' => 'Calle Hola 2',
                'capacity' => 100,
                'user_id' => 2,
                'visible' => true,
            ],
            [
                'name' => 'Maquiavelo',
                'total_price' => 18.99,
                'categories_id' => 3,
                'image' => '../../img/maquiavelo.jpg',
                'ubication' => 'Calle Hola 3',
                'capacity' => 100,
                'user_id' => 3,
                'visible' => true,
            ],
            [
                'name' => 'Blanca Paloma',
                'total_price' => 29.99,
                'categories_id' => 4,
                'image' => '../../img/blancaPaloma.jpg',
                'ubication' => 'Calle Hola 4',
                'capacity' => 100,
                'user_id' => 4,
                'visible' => true,
            ],
            [
                'name' => 'Río Grande',
                'total_price' => 22.50,
                'categories_id' => 5,
                'image' => '../../img/rioGrande.jpg',
                'ubication' => 'Calle Hola 5',
                'capacity' => 100,
                'user_id' => 5,
                'visible' => true,
            ],
            [
                'name' => 'Bilio',
                'total_price' => 20.50,
                'categories_id' => 5,
                'image' => '../../img/bilio.jpg',
                'ubication' => 'Calle Hola 6',
                'capacity' => 100,
                'user_id' => 6,
                'visible' => true,
            ],
            [
                'name' => 'Abades Triana',
                'total_price' => 20.00,
                'categories_id' => 1,
                'image' => '../../img/abades.jpg',
                'ubication' => 'Calle Hola 7',
                'capacity' => 100,
                'user_id' => 7,
                'visible' => true,
            ],
            [
                'name' => 'Las Dunas',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/Dunas.jpg',
                'ubication' => 'Calle Hola 8',
                'capacity' => 100,
                'user_id' => 8,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Bocanegra',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/bocanegra.jpg',
                'ubication' => 'Calle Hola 9',
                'capacity' => 100,
                'user_id' => 9,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Coloniales',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/coloniales.jpg',
                'ubication' => 'Calle Hola 10',
                'capacity' => 100,
                'user_id' => 10,
                'visible' => true,
            ],
            [
                'name' => 'Taberna El Arenal',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/Arenal.jpg',
                'ubication' => 'Calle Hola 11',
                'capacity' => 100,
                'user_id' => 11,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Antonio Romero',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/antonioRomero.jpg',
                'ubication' => 'Calle Hola 12',
                'capacity' => 100,
                'user_id' => 12,
                'visible' => true,
            ],
            [
                'name' => 'Restaurante San Marco (Santa Cruz, Sevilla)',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/SanMarco.jpg',
                'ubication' => 'Calle Hola 13',
                'capacity' => 100,
                'user_id' => 13,
                'visible' => true,
            ],
            [
                'name' => 'María Trifulca',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/mariaTrifulca.jpg',
                'ubication' => 'Calle Hola 14',
                'capacity' => 100,
                'user_id' => 14,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Almazara',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/almazara.jpg',
                'ubication' => 'Calle Hola 15',
                'capacity' => 100,
                'user_id' => 15,
                'visible' => true,
            ],
            [
                'name' => 'Patio San Eloy (Triana)',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/SanEloyTriana.jpg',
                'ubication' => 'Calle Hola 16',
                'capacity' => 100,
                'user_id' => 16,
                'visible' => true,
            ],
            [
                'name' => 'Patio San Eloy (Santa Catalina)',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/SanEloyStaCatalina.jpg',
                'ubication' => 'Calle Hola 17',
                'capacity' => 100,
                'user_id' => 17,
                'visible' => true,
            ],
            [
                'name' => 'Bar Casemiro',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/casemiro.jpg',
                'ubication' => 'Calle Hola 18',
                'capacity' => 100,
                'user_id' => 18,
                'visible' => true,
            ],
            [
                'name' => 'Amanecer (Alameda de Hércules, Sevilla)',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/amanecer.png',
                'ubication' => 'Calle Hola 19',
                'capacity' => 100,
                'user_id' => 19,
                'visible' => true,
            ],
            [
                'name' => 'Avelino',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/avelino.jpg',
                'ubication' => 'Calle Hola 20',
                'capacity' => 100,
                'user_id' => 20,
                'visible' => true,
            ],
            [
                'name' => 'Aderezo',
                'total_price' => 35.50,
                'categories_id' => 2,
                'image' => '../../img/aderezo.jpg',
                'ubication' => 'Calle Hola 21',
                'capacity' => 100,
                'user_id' => 21,
                'visible' => true,
            ],
        ]);
    }
}
